# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: takewiki's blog on github.io
email: hulilei@takewiki.com
theme: jekyll-theme-leap-day
description: > # this means to ignore newlines until "baseurl:"
  用于记录关于takewiki的技术文章并将托管在github.io上.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://takewiki.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb remark the file.
github_username:  takewiki

# Build settings
markdown: kramdown
